name: Release

on:
  push:
    tags:
      - 'v*'
    
permissions:
    id-token: write
    contents: read
    issues: write
    pull-requests: write
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        pip install pipenv
        pipenv install --dev

    - name: Create a release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v${{ env.NEXT_TAG }}
        release_name: Release v${{ env.NEXT_TAG }}
        draft: false
        prerelease: false
